// <auto-generated />
using System;
using FabrikaERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabrikaERP.Migrations
{
    [DbContext(typeof(FabrikaDbContext))]
    [Migration("20260323215002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("FabrikaERP.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 3, 23, 19, 50, 1, 989, DateTimeKind.Utc).AddTicks(6772),
                            IsRead = false,
                            IsResolved = false,
                            MachineId = 3,
                            Message = "Pres Makinesi B-1 beklenmedik durma. Teknisyen çağırıldı.",
                            Severity = 2,
                            Title = "Makine B-7 Ani Durdu"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 3, 23, 20, 50, 1, 989, DateTimeKind.Utc).AddTicks(7092),
                            IsRead = false,
                            IsResolved = false,
                            Message = "Oluklu Mukavva Kutu stoku minimum seviyenin altına düştü.",
                            Severity = 1,
                            Title = "Hammadde Stok Kritik"
                        },
                        new
                        {
                            Id = 3,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 20, 1, 989, DateTimeKind.Utc).AddTicks(7098),
                            IsRead = false,
                            IsResolved = false,
                            Message = "A Vardiyası 16:00'da sona eriyor. Shift geçişi hazırlanıyor.",
                            Severity = 0,
                            Title = "A Vardiyası Bitiyor"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 3, 23, 18, 50, 1, 989, DateTimeKind.Utc).AddTicks(7110),
                            IsRead = false,
                            IsResolved = false,
                            MachineId = 6,
                            Message = "WLD-02 elektriki arıza tespit edildi. Bakım ekibi yönlendiriliyor.",
                            Severity = 2,
                            Title = "Kaynak Robot C-2 Arıza"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 5, 1, 989, DateTimeKind.Utc).AddTicks(7112),
                            IsRead = false,
                            IsResolved = false,
                            Message = "Son 2 saatte hata oranı %1.8'e yükseldi. Kalite kontrol devreye girdi.",
                            Severity = 1,
                            Title = "Kalite Anomalisi Tespit"
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxStock")
                        .HasColumnType("REAL");

                    b.Property<double>("MinStock")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StockQty")
                        .HasColumnType("REAL");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitCost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Code = "HM-001",
                            MaxStock = 5000.0,
                            MinStock = 500.0,
                            Name = "Çelik Profil 40x40",
                            StockQty = 2500.0,
                            Supplier = "MetalSan A.Ş.",
                            Unit = "kg",
                            UnitCost = 12.5,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(9230)
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Code = "HM-002",
                            MaxStock = 500.0,
                            MinStock = 50.0,
                            Name = "Alüminyum Sac 2mm",
                            StockQty = 150.0,
                            Supplier = "AlümTürk",
                            Unit = "m²",
                            UnitCost = 85.0,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1234)
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Code = "HM-003",
                            MaxStock = 2000.0,
                            MinStock = 200.0,
                            Name = "Plastik Granül ABS",
                            StockQty = 800.0,
                            Supplier = "Polimer A.Ş.",
                            Unit = "kg",
                            UnitCost = 45.0,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1299)
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Code = "YP-001",
                            MaxStock = 1000.0,
                            MinStock = 100.0,
                            Name = "Dişli Grubu A-12",
                            StockQty = 320.0,
                            Unit = "adet",
                            UnitCost = 125.0,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1301)
                        },
                        new
                        {
                            Id = 5,
                            Category = 3,
                            Code = "BP-001",
                            MaxStock = 50.0,
                            MinStock = 5.0,
                            Name = "Hidrolik Pompa Filtresi",
                            StockQty = 12.0,
                            Supplier = "HidroTek",
                            Unit = "adet",
                            UnitCost = 380.0,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1302)
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Code = "BP-002",
                            MaxStock = 100.0,
                            MinStock = 10.0,
                            Name = "Rulman 6205-2RS",
                            StockQty = 48.0,
                            Supplier = "SKF Türkiye",
                            Unit = "adet",
                            UnitCost = 95.0,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1304)
                        },
                        new
                        {
                            Id = 7,
                            Category = 4,
                            Code = "TK-001",
                            MaxStock = 500.0,
                            MinStock = 50.0,
                            Name = "Kesme Yağı ISO 46",
                            StockQty = 220.0,
                            Supplier = "Mobil",
                            Unit = "lt",
                            UnitCost = 18.0,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1305)
                        },
                        new
                        {
                            Id = 8,
                            Category = 5,
                            Code = "PK-001",
                            MaxStock = 5000.0,
                            MinStock = 500.0,
                            Name = "Oluklu Mukavva Kutu",
                            StockQty = 4.0,
                            Supplier = "Karton A.Ş.",
                            Unit = "adet",
                            UnitCost = 2.5,
                            UpdatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(1307)
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.KpiSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveMachines")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedWorkOrders")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OeePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("PendingWorkOrders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("QualityRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMachines")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("KpiSnapshots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveAlerts = 3,
                            ActiveMachines = 6,
                            CompletedWorkOrders = 2,
                            OeePercent = 87.299999999999997,
                            PendingWorkOrders = 3,
                            ProductionRate = 1247,
                            QualityRate = 99.099999999999994,
                            Timestamp = new DateTime(2026, 3, 23, 21, 50, 1, 992, DateTimeKind.Utc).AddTicks(2021),
                            TotalMachines = 8
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastService")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextService")
                        .HasColumnType("TEXT");

                    b.Property<double>("OeeCurrent")
                        .HasColumnType("REAL");

                    b.Property<double>("OeeTarget")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CNC-01",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(6677),
                            Department = "Üretim",
                            IsActive = true,
                            Name = "CNC Torna A-1",
                            OeeCurrent = 87.299999999999997,
                            OeeTarget = 85.0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "CNC-02",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8371),
                            Department = "Üretim",
                            IsActive = true,
                            Name = "CNC Torna A-2",
                            OeeCurrent = 82.099999999999994,
                            OeeTarget = 85.0,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "PRS-01",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8378),
                            Department = "Presleme",
                            IsActive = true,
                            Name = "Pres Makinesi B-1",
                            OeeCurrent = 0.0,
                            OeeTarget = 80.0,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "PRS-02",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8379),
                            Department = "Presleme",
                            IsActive = true,
                            Name = "Pres Makinesi B-2",
                            OeeCurrent = 79.5,
                            OeeTarget = 80.0,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "WLD-01",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8381),
                            Department = "Kaynak",
                            IsActive = true,
                            Name = "Kaynak Robot C-1",
                            OeeCurrent = 91.200000000000003,
                            OeeTarget = 90.0,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "WLD-02",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8405),
                            Department = "Kaynak",
                            IsActive = true,
                            Name = "Kaynak Robot C-2",
                            OeeCurrent = 0.0,
                            OeeTarget = 90.0,
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "ASM-01",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8408),
                            Department = "Montaj",
                            IsActive = true,
                            Name = "Montaj Hattı D-1",
                            OeeCurrent = 84.799999999999997,
                            OeeTarget = 85.0,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Code = "PKG-01",
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 988, DateTimeKind.Utc).AddTicks(8409),
                            Department = "Paketleme",
                            IsActive = true,
                            Name = "Paketleme E-1",
                            OeeCurrent = 0.0,
                            OeeTarget = 75.0,
                            Status = 1
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Technician")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MaintenanceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(7743),
                            MachineId = 1,
                            ScheduledAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Technician = "Ahmet Yılmaz",
                            Title = "Periyodik Yağlama",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 991, DateTimeKind.Utc).AddTicks(7283),
                            MachineId = 6,
                            ScheduledAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            StartedAt = new DateTime(2026, 3, 23, 19, 50, 1, 991, DateTimeKind.Utc).AddTicks(7305),
                            Status = 1,
                            Technician = "Mehmet Kaya",
                            Title = "Elektrik Arıza Giderme",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CompletedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Cost = 1250.0,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 991, DateTimeKind.Utc).AddTicks(7610),
                            MachineId = 4,
                            ScheduledAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            StartedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            Technician = "Ali Demir",
                            Title = "Filtre Değişimi",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CompletedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Cost = 3200.0,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 991, DateTimeKind.Utc).AddTicks(8132),
                            MachineId = 3,
                            ScheduledAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            StartedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            Technician = "Ahmet Yılmaz",
                            Title = "Acil Pnömatik Tamir",
                            Type = 3
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.QualityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("QualityRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "BC-2024-001",
                            InspectedAt = new DateTime(2026, 3, 23, 17, 50, 1, 992, DateTimeKind.Utc).AddTicks(827),
                            InspectorId = "QC-01",
                            ProductName = "Dişli Grubu A-12",
                            Result = 0,
                            WorkOrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "BC-2024-002",
                            FailReason = "Çap toleransı dışı",
                            InspectedAt = new DateTime(2026, 3, 23, 18, 50, 1, 992, DateTimeKind.Utc).AddTicks(1213),
                            InspectorId = "QC-01",
                            ProductName = "Dişli Grubu A-12",
                            Result = 1,
                            WorkOrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "BC-2024-003",
                            InspectedAt = new DateTime(2026, 3, 23, 19, 50, 1, 992, DateTimeKind.Utc).AddTicks(1217),
                            InspectorId = "QC-02",
                            ProductName = "Rulman Seti C-3",
                            Result = 0,
                            WorkOrderId = 3
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "BC-2024-004",
                            InspectedAt = new DateTime(2026, 3, 23, 20, 50, 1, 992, DateTimeKind.Utc).AddTicks(1219),
                            InspectorId = "QC-02",
                            ProductName = "Rulman Seti C-3",
                            Result = 0,
                            WorkOrderId = 3
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sistem Yöneticisi",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fabrika Müdürü",
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Makine Operatörü",
                            RoleName = "Operator"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kalite Kontrol Uzmanı",
                            RoleName = "Quality"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bakım Teknisyeni",
                            RoleName = "Maintenance"
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            ShiftName = "Gündüz",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(1, 0, 0, 0, 0),
                            ShiftName = "Akşam",
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            ShiftName = "Gece",
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FabrikaERP.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedQty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducedQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectedQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("MachineId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualStart = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(2004),
                            MachineId = 1,
                            OrderNumber = "WO-2024-0891",
                            PlannedEnd = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQty = 500,
                            PlannedStart = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProducedQty = 390,
                            ProductCode = "YP-001",
                            ProductName = "Dişli Grubu A-12",
                            RejectedQty = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ActualStart = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(4610),
                            MachineId = 3,
                            OrderNumber = "WO-2024-0890",
                            PlannedEnd = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQty = 200,
                            PlannedStart = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProducedQty = 90,
                            ProductCode = "YP-002",
                            ProductName = "Gövde Kasası B-7",
                            RejectedQty = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            ActualEnd = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualStart = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(4614),
                            MachineId = 5,
                            OrderNumber = "WO-2024-0889",
                            PlannedEnd = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQty = 1000,
                            PlannedStart = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProducedQty = 1000,
                            ProductCode = "BP-006",
                            ProductName = "Rulman Seti C-3",
                            RejectedQty = 9,
                            Status = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(4850),
                            MachineId = 6,
                            OrderNumber = "WO-2024-0888",
                            PlannedEnd = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQty = 350,
                            PlannedStart = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProducedQty = 0,
                            ProductCode = "YP-003",
                            ProductName = "Piston Grubu D-1",
                            RejectedQty = 0,
                            Status = 5
                        },
                        new
                        {
                            Id = 5,
                            ActualEnd = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualStart = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 3, 23, 21, 50, 1, 989, DateTimeKind.Utc).AddTicks(4854),
                            MachineId = 7,
                            OrderNumber = "WO-2024-0887",
                            PlannedEnd = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQty = 250,
                            PlannedStart = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProducedQty = 250,
                            ProductCode = "FP-001",
                            ProductName = "Montaj Kiti E-2",
                            RejectedQty = 1,
                            Status = 3
                        });
                });

            modelBuilder.Entity("FabrikaERP.Models.Alert", b =>
                {
                    b.HasOne("FabrikaERP.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("FabrikaERP.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("FabrikaERP.Models.Machine", "Machine")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("MachineId");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("FabrikaERP.Models.QualityRecord", b =>
                {
                    b.HasOne("FabrikaERP.Models.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("FabrikaERP.Models.User", b =>
                {
                    b.HasOne("FabrikaERP.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FabrikaERP.Models.Shift", "Shift")
                        .WithMany("Users")
                        .HasForeignKey("ShiftId");

                    b.Navigation("Role");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FabrikaERP.Models.WorkOrder", b =>
                {
                    b.HasOne("FabrikaERP.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("FabrikaERP.Models.Machine", "Machine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("MachineId");

                    b.Navigation("AssignedUser");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("FabrikaERP.Models.Machine", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("FabrikaERP.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FabrikaERP.Models.Shift", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
